server:
  port: 8080

spring:
  application:
    name: indian-vehicle-invoice-service
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      continue-on-error: false

logging:
  level:
    com.vehicle.invoice: DEBUG
    org.springframework.web: DEBUG
